services:
  frontend:
    image: ghcr.io/awfulwoman/memorybank-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/awfulwoman/memorybank-backend:latest
    environment:
      - DJANGO_SECRET_KEY="" # Set this key in a secure manner
    volumes:
      - ./data/db:/data/db
      - ./data/media:/data/media
