services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8102:8000"
    environment:
      - DJANGO_SECRET_KEY="" # Set this key in a secure manner
    volumes:
      - ./data/db:/data/db
      - ./data/media:/data/media
