# Generated by Django 6.0.3 on 2026-03-22 14:26

from django.db import migrations


def create_default_group(apps, schema_editor):
    Group = apps.get_model('core', 'Group')
    if not Group.objects.filter(name='Default').exists():
        Group.objects.create(name='Default', default_split_method='equal')


def reverse_default_group(apps, schema_editor):
    Group = apps.get_model('core', 'Group')
    Group.objects.filter(name='Default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group'),
    ]

    operations = [
        migrations.RunPython(create_default_group, reverse_default_group),
    ]
