# Generated by Django 6.0.3 on 2026-03-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='mdi-shape-outline', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='mdi-account-group', max_length=50),
        ),
    ]
