name: Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps: []

  test-frontend:
    runs-on: ubuntu-latest
    steps: []

  publish-backend:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps: []

  publish-frontend:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps: []
